List available environments in set-environment

diff --git a/scripts/local/bin/set-environment b/scripts/local/bin/set-environment
--- a/scripts/local/bin/set-environment
+++ b/scripts/local/bin/set-environment
@@ -15,14 +15,36 @@
 
 set -e
 
+THIS_DIR=$(cd "$(dirname "$0")" && pwd)
+ENVIRONMENTS_DIR=$(cd "$THIS_DIR" && cd ../environments && pwd)
+
+list_environments() {
+  echo "Available environments:"
+  pushd "$ENVIRONMENTS_DIR" > /dev/null
+  dirs=(*/)
+  for dir in "${dirs[@]}"; do
+    name="${dir%/}"
+    if [ "$name" == "*" ]; then
+      echo "None found"
+    else
+      echo "$name"
+    fi
+  done
+  popd > /dev/null
+}
+
 if [ "$#" -lt 1 ]; then
 	echo "Usage: $0 <uniqueId>"
+  list_environments
 	exit 1
 fi
 
 INSTANCE_ID=$1
 
-THIS_DIR=$(cd "$(dirname "$0")" && pwd)
-ENVIRONMENTS_DIR=$(cd "$THIS_DIR" && cd ../environments && pwd)
-
-echo "$INSTANCE_ID" > "$ENVIRONMENTS_DIR/current.txt"
+if [ -d "$ENVIRONMENTS_DIR/$INSTANCE_ID" ]; then
+  echo "$INSTANCE_ID" > "$ENVIRONMENTS_DIR/current.txt"
+else
+  echo "Environment not found: $INSTANCE_ID"
+  list_environments
+	exit 1
+fi
